### ISSUE TITLE
Variables looked for in uppercase instead of specified format: SENDERNAME is not defined instead of senderName

### ISSUE THREAD

**Issue by alexphiev** [alexzaganelli/strapi-plugin-email-designer#124]
### Describe the bug

I need to send my email template variables from the code with upper case even though the template mentions `{{= variableName }}` in this format. 

### Steps to reproduce the behavior

1. Create a template with the`{{= senderName }}` variable in any text or in the subject
2. Save and use it in the code with the variable sent as `senderName` with the method: `strapi.plugins["email-designer"].services.email.sendTemplatedEmail()`

### Additional context

It seems to be happening only in PROD environment but not 100% sure.

**Comment by dzpincus** [comment]
I'm also experiencing this issue. Any resolution?

**Comment by creazy231** [comment]
Could you explain what do you mean by having to send variables in uppercase by giving us an example on how it works and on how it not works?

**Comment by dalton5** [comment]
Yes I have the same issue. I investigated. It's due to htmltotext method. It uses the lib html to text and for H1 or H2 it puts by default uppercase. You need to remove this otherwise when we call a variable lowercase in a title it can't find it because the text version transforms in uppercase.

See below the description from htmltotext:
uppercase | true | heading | By default, headings (<h1>, <h2>, etc) are uppercased.Set this to false to leave headings as they are.

Please fix it asap because I have the same issue. Thanks,
