### ISSUE TITLE
Can not add custom font to template 

### ISSUE THREAD

**Issue by Manukyanq** [alexzaganelli/strapi-plugin-email-designer#21]
Hi there. Can I somehow add different fonts to my templates? Thanks in advance ) 
![image](https://user-images.githubusercontent.com/42891870/111282159-c1af6300-864e-11eb-945b-5b4d135771b7.png)

**Comment by creazy231** [comment]
This plugin uses unlayer to generate email templates. Currently there is no way to inject custom fonts into unlayer without editing the plugin itself.
But since unlayer supports custom font injection I think someone if not me could add this as a feature to the plugin to manage custom fonts inside the strapi backend.

**Comment by tbanys** [comment]
@creazy231 maybe you can send example where I could see how to add custom fonts?

I would try to add it for my project.

**Comment by creazy231** [comment]
@tbanys sure, it's documented here: https://docs.unlayer.com/docs/font-management
but I just noticed, that this is a Premium Feature for Unlayer but maybe you can find something is working for you
