### ISSUE TITLE
Updating to 0.2.9 results in empty templates

### ISSUE THREAD

**Issue by creazy231** [alexzaganelli/strapi-plugin-email-designer#25]
Hey just updated to the newest version 0.2.9 and after running `yarn && yarn build && yarn develop` all my created templates are empty.
Took a look into the network tab and can't see any query to the templates anymore. I think thats the reason for the problem.

**Comment by creazy231** [comment]
Problem appears here: https://github.com/alexzaganelli/strapi-plugin-email-designer/blob/main/admin/src/containers/Designer/index.js#L92
If I remove `!emailEditorRef.current` everything works but I don't know why, I'm not an react expert tbh.

**Comment by pr0gr8mm3r** [comment]
Just noticed that too. That line hasn't changed, but [line 206](https://github.com/alexzaganelli/strapi-plugin-email-designer/blob/151737406de22310a87ee7ceeeb3d5cc3a1598d3/admin/src/containers/Designer/index.js#L206) did. Because `configLoaded` is only set to true after that check, nothing is loaded. I will look into a fix.

**Comment by pr0gr8mm3r** [comment]
Ok, so I added that check in line 206 to delay initialization until the config was loaded, because the unlayer editor doesn't update even when using state. I'm also pretty new to react, so any input is appreciated.

@alexzaganelli is there a way to undo publishing 0.2.9 or set the latest stable version back to 0.2.7?

**Comment by pr0gr8mm3r** [comment]
Ok, the solution seems to be to re-run that side-effect once the config has loaded. To me that seems a bit hacky, but it works and it's the only thing I can come up with with my limited knowledge...
