### ISSUE TITLE
[Strapi V4] Learn how to use templates link is not working

### ISSUE THREAD

**Issue by Flowko** [alexzaganelli/strapi-plugin-email-designer#79]
![image](https://user-images.githubusercontent.com/35883748/153706676-4a4aa762-1fed-4ac1-b10c-8f7805cdab4d.png)

it redirects to this page http://localhost:1337/admin/plugins/email-designer/how-to and shows nothing

**Comment by alexzaganelli** [comment]
Hi @Flowko

thank you for your signal. As you can imagine refactoring a plugin require a lot of time and I'm trying to do my best, working during my extra time. I'm on the _HowTo_ page since this morning and it should be updated soon. I left this task at the end since I think it's the less important.

**Comment by Flowko** [comment]
ah yes i tottaly get it, thanks for the hard work mate

**Comment by alexzaganelli** [comment]
Should be fixed on v2.0.5 ([9140608](https://github.com/alexzaganelli/strapi-plugin-email-designer/commit/914060835c55008c79b57ce09baa4a2c384f5e25))

**Comment by Flowko** [comment]
working on v2.0.5
